spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "${NGROK_URL}/login/oauth2/code/google"
          naver:
            redirect-uri: "http://192.168.0.109:8080/login/oauth2/code/naver"