spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://15.164.67.216:8080/login/oauth2/code/google"
          naver:
            redirect-uri: "http://15.164.67.216:8080/login/oauth2/code/naver"

app:
  oauth2:
    redirect-base-url: "dorandoran-scheme://oauth2/callback"